version: '3.7'

services:

        web:
                build: .
                command:
                sh -c "wait-for db:5432 && wait-for rabbit:5672 &&
                python /code/manage.py migrate &&
                python /code/manage.py runserver 0.0.0.0:8080"

                environment:
                        - ENVIRONMENT=development
                        - DEBUG=1
                volumes:
                        - .:/code
                ports:
                        - 8000:8000
                depends_on:
                        - db
                        - rabbit

        rabbit:
                image: rabbitmq:3-management
                container_name: rabbit
                hostname: rabbit
                environment:
                        - RABBITMQ_DEFAULT_USER=admin
                        - RABBITMQ_DEFAULT_PASS=admin
                        - RABBITMQ_DEFAULT_VHOST=/
                ports:
                        - "5682:5672"
                        - "15682:15672"

        worker:
                image: backend-image
                restart: on-failure
                command: >
                        sh -c "wait-for web:8000 &&
                               celery -A config worker -l info /tmp/celerybeat-schedule"
                depends_on:
                        - web
                        - rabbit
                        - db

        db:
                build: postgres/
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
        postgres_data:

